eol-uchile/argocd-config

argocd-ingress/ingress.yaml, graylog/graylog.yaml, graylog/ingress.yaml, metabase/ingress.yaml, monitoring/ingress.yaml
Co-authored-by: Felipe Espinoza <fdns@users.noreply.github.com>
Co-authored-by: Matías Salinas Soto <matiassalinas@users.noreply.github.com>
Co-authored-by: Luis Santana <luis.santana101@gmail.com>
=> Update domains and subdomains to eol-ing.uchile.cl

edx-backup/eol.yml, edx-backup/uabierta.yaml
Minio backups should run on low demand times. i.e. 3AM
=> Split backup workloads

monitoring/additional-probes.yaml
Temporary change so that the guaripolo bot stops issuing alerts associated with this URL.
=> [temp] Disabled URL cajalosandes in staticConfig

projects/kustomization.yaml, projects/test-host-eol/project.yaml
Agrega proyecto para Test de EOL para crear el nuevo namespace.
=> Add project test-host-eol to list

projects/test-host-eol/project.yaml
Agrega namespace del proyecto como objeto
=> Added namespace `test-eol` to project

graylog/graylog.yaml, otrs/otrs.yaml
Change default email of graylog and otrs to improve deliverability (SPF)
=> Change sender email address to improve deliverability

projects/edx-uabierta/project.yaml
[Docs](https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/)
=> [Uabierta] Disabled automatic project sync

projects/edx-ou-staging/project.yaml, projects/kustomization.yaml
=> Add project edx-ou-staging

projects/kustomization.yaml, projects/test-host-eol/project.yaml, test-host-eol/ingress.yaml, test-host-eol/kustomization.yaml, test-host-eol/nginx-s3-gateway.yaml, test-host-eol/secrets/s3-settings.yaml
- Project `test-host-eol` enabled
- Updated ingress notation
=> chore(test-host-eol): project enabled; updated ingress notation

emi-project/ingress.yaml, emi-project/kustomization.yaml, emi-project/secrets/emi-wordpress.yaml, emi-project/wordpress-fpm.yaml, emi-project/wordpress-nginx.yaml, projects/emi-project/project.yaml, projects/kustomization.yaml
=> chore(emi): update project definition & add to new argocd

.github/workflows/kustomize.yml, projects/kustomization.yaml
=>   chore: remove emi-project from old ArgoCD

.github/workflows/kustomize.yml, projects/kustomization.yaml
=> chore: remove otrs  project from old ArgoCD

monitoring/additional-probes.yaml, monitoring/alerts.yaml, monitoring/discord-secrets.yaml, monitoring/discord.yaml, monitoring/external/elastic-external/staging.yaml, monitoring/external/minio-external/staging.yaml, monitoring/external/mongodb-external/eol.yaml, monitoring/external/mysql-external/eol.yaml, monitoring/external/mysql-external/staging.yaml, monitoring/external/node-exporter.yaml, monitoring/external/redis-external/eol.yaml, monitoring/external/redis-external/staging.yaml, monitoring/ingress.yaml, monitoring/kustomization.yaml, monitoring/psp.yaml, monitoring/secret.yaml, projects/kustomization.yaml, projects/monitoring/project.yaml
=> chore(monitoring): update project definition & add to new argocd

portal-eol/ingress.yaml, portal-eol/kustomization.yaml, portal-eol/portal-eol.yaml, projects/kustomization.yaml, projects/portal-eol/project.yaml
=> chore(portal-eol): update project definition & add to new argocd

projects/monitoring/project.yaml
Fix removed AppProject destinations in `monitoring`.
=> chore(monitoring): fix removed destinations

.github/workflows/kustomize.yml, .github/workflows/update-docs.yml, .github/workflows/update-portal.yml
Align kustomize binary used in workflows with the same version bundled into ArgoCD v3.1.0 image.
=> ci: Align kustomize version with argocd 3.1.0 embedded one

projects/edx-virtuallabx/virtuallabx.yaml, projects/kustomization.yaml, projects/norteamericano/edx-norteamericano.yaml
- Project `edx-norteamericano`:
- Project `edx-virtuallabx`:
=> chore: update edx-norteamericano & edx-virtuallabx project definition; add to new argocd 

projects/edx-ou-staging/project.yaml, projects/edx-staging/project.yaml, projects/kustomization.yaml
- Project `edx-staging`:
- Project `edx-ou-staging`:
=>  chore: update edx-staging & edx-ou-staging project definition; add to new argocd

projects/kustomization.yaml
Remove `edx-sandbox` project from old ArgoCD
=> chore(edx-sandbox): project removed from kustomization

projects/edx-uabierta/project.yaml, projects/kustomization.yaml
=> chore(edx-uabierta): update project definition; enabled in kustomization

projects/kustomization.yaml
Remove `edx-dgd` project from old ArgoCD
=> chore(edx-dgd): project removed from kustomization
